import { FormEvent, useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { api, ApiError, ChatbotType } from "./api";

type Agent = { id: ChatbotType; name: string; icon: string; prompts: string[]; notice?: string };
type Message = { role: "user" | "assistant"; content: string };

const agents: Agent[] = [
  { id: "engineer", name: "Engineer", icon: "⌘", prompts: ["Help me debug a TypeScript error", "Explain this system design", "Review my API approach"] },
  { id: "doctor", name: "Doctor", icon: "✚", prompts: ["Explain these common symptoms", "How can I prepare for a doctor visit?", "What does this lab term mean?"], notice: "Educational information only — not medical advice, diagnosis, or a substitute for a clinician." },
  { id: "lawyer", name: "Lawyer", icon: "§", prompts: ["Explain a contract clause", "What should I consider before signing?", "Help me prepare questions for a lawyer"], notice: "Educational information only — not legal advice. Consult a qualified lawyer for your situation." },
];
const passwordIssue = (value: string) => !/^.{8,}$/.test(value) ? "Use at least 8 characters." : !/[A-Z]/.test(value) ? "Include an uppercase letter." : !/[a-z]/.test(value) ? "Include a lowercase letter." : !/\d/.test(value) ? "Include a number." : !/[^A-Za-z0-9]/.test(value) ? "Include a special character." : "";

export default function App() {
  const [token, setToken] = useState<string | null>(null);
  const [email, setEmail] = useState("");
  const [authMessage, setAuthMessage] = useState("");
  return token ? <Chat token={token} email={email} onLogout={(expired = false) => { setToken(null); setEmail(""); setAuthMessage(expired ? "Your session has expired. Please log in again." : ""); }} /> : <Auth onLogin={(newToken, newEmail) => { setToken(newToken); setEmail(newEmail); setAuthMessage(""); }} initialMessage={authMessage} />;
}

function Auth({ onLogin, initialMessage }: { onLogin: (token: string, email: string) => void; initialMessage: string }) {
  const [tab, setTab] = useState<"login" | "register">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [visible, setVisible] = useState(false); const [error, setError] = useState(initialMessage); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setNotice(""); if (tab === "register") { const issue = passwordIssue(password); if (issue) return setError(issue); } setBusy(true); try { if (tab === "login") { const result = await api.login(email, password); onLogin(result.access_token, email); } else { await api.register(email, password); setNotice("Registration successful. Please log in."); setTab("login"); setPassword(""); } } catch (e) { setError((e as ApiError).message); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-card"><div className="brand-mark">✦</div><p className="eyebrow">AI SPECIALISTS, ONE PLACE</p><h1>Agents Network</h1><p className="muted">Ask better questions. Get focused help.</p><div className="tabs" role="tablist"><button className={tab === "login" ? "active" : ""} onClick={() => { setTab("login"); setError(""); }}>Login</button><button className={tab === "register" ? "active" : ""} onClick={() => { setTab("register"); setError(""); }}>Register</button></div><form onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" /></label><label>Password<div className="password"><input required type={visible ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} autoComplete={tab === "login" ? "current-password" : "new-password"} /><button type="button" onClick={() => setVisible(!visible)}>{visible ? "Hide" : "Show"}</button></div></label>{tab === "register" && <p className="form-hint">8+ characters with uppercase, lowercase, number, and special character.</p>}{error && <p className="alert error" role="alert">{error}</p>}{notice && <p className="alert success">{notice}</p>}<button className="primary" disabled={busy}>{busy ? "Please wait…" : tab === "login" ? "Login" : "Create account"}</button></form></section></main>;
}

function Chat({ token, email, onLogout }: { token: string; email: string; onLogout: (expired?: boolean) => void }) {
  const [agent, setAgent] = useState<Agent>(agents[0]); const [messages, setMessages] = useState<Message[]>([]); const [conversationId, setConversationId] = useState<number | null>(null); const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [drawer, setDrawer] = useState(false); const end = useRef<HTMLDivElement>(null);
  useEffect(() => end.current?.scrollIntoView({ behavior: "smooth" }), [messages, busy]);
  const clear = () => { setMessages([]); setConversationId(null); setError(""); setInput(""); };
  const chooseAgent = (next: Agent) => { if (next.id === agent.id) return; if (conversationId !== null && !window.confirm("Switching agents will discard this conversation. Continue?")) return; setAgent(next); clear(); setDrawer(false); };
  const send = async (message = input.trim()) => { if (!message || busy || message.length > 10000) return; setInput(""); setError(""); setMessages(current => [...current, { role: "user", content: message }]); setBusy(true); try { const result = await api.sendChatMessage(token, message, conversationId, agent.id); setConversationId(result.conversation_id); setMessages(current => [...current, { role: "assistant", content: result.response }]); } catch (e) { const apiError = e as ApiError; if (apiError.status === 401) { onLogout(true); return; } setError(apiError.message); } finally { setBusy(false); } };
  const logout = async () => { try { await api.logout(token); } catch { /* Local logout must always complete. */ } onLogout(); };
  return <div className="shell"><aside className={drawer ? "sidebar open" : "sidebar"}><div className="sidebar-head"><span className="brand-mark small">✦</span><strong>Agents Network</strong><button className="mobile-close" onClick={() => setDrawer(false)}>×</button></div><button className="new-chat" onClick={clear} disabled={busy}>＋ New chat</button><p className="sidebar-label">SPECIALIST</p><nav>{agents.map(item => <button key={item.id} disabled={busy} className={agent.id === item.id ? "agent active" : "agent"} onClick={() => chooseAgent(item)}><span>{item.icon}</span>{item.name}</button>)}</nav><div className="account"><span>{email}</span><button onClick={logout}>Log out <span>↗</span></button></div></aside>{drawer && <button className="backdrop" aria-label="Close menu" onClick={() => setDrawer(false)} />}
    <main className="chat"><header><button className="menu" aria-label="Open menu" onClick={() => setDrawer(true)}>☰</button><div><p className="eyebrow">SPECIALIST AGENT</p><h2>{agent.name}</h2></div><span className="status"><i /> Online</span></header><section className="messages">{messages.length === 0 ? <div className="empty"><div className="agent-icon">{agent.icon}</div><h3>How can I help?</h3><p>I’m your {agent.name.toLowerCase()} agent. Start with a question or try one of these.</p><div className="suggestions">{agent.prompts.map(prompt => <button key={prompt} onClick={() => send(prompt)} disabled={busy}>{prompt}<span>↗</span></button>)}</div></div> : messages.map((message, index) => <article className={`message ${message.role}`} key={index}><div className="avatar">{message.role === "user" ? email.slice(0, 1).toUpperCase() : agent.icon}</div><div className="bubble">{message.role === "assistant" ? <ReactMarkdown remarkPlugins={[remarkGfm]}>{message.content}</ReactMarkdown> : message.content}</div></article>)}{busy && <article className="message assistant"><div className="avatar">{agent.icon}</div><div className="bubble typing"><span /><span /><span /></div></article>}<div ref={end} /></section>{agent.notice && <p className="notice">{agent.notice}</p>}{error && <div className="chat-error">{error}<button onClick={() => send(messages.at(-1)?.content)}>Retry</button></div>}<form className="composer" onSubmit={e => { e.preventDefault(); send(); }}><textarea value={input} onChange={e => setInput(e.target.value)} placeholder={`Message ${agent.name}…`} maxLength={10000} disabled={busy} rows={1} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} /><button aria-label="Send message" disabled={busy || !input.trim()}>↑</button></form><p className="footer-note">Agents Network can make mistakes. Verify important information.</p></main></div>;
}
